name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/eslint/
          key: ${{ runner.os }}-eslint-${{ hashFiles('**/pnpm-lock.yaml', '**/.eslintrc.cjs') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Run linter
        run: pnpm run lint --cache-strategy content --cache-location ~/.cache/eslint/template-ts

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Test
        run: pnpm run test
