name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        script:
          - lint
          - build
          - test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ^20.11

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ^8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}
