name: coverage

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install
        uses: ./.github/actions/install

      - name: Run coverage
        run: |
          echo 'COVERAGE_OUTPUT<<EOF' >> $GITHUB_ENV
          pnpm run coverage >> $GITHUB_ENV
          echo EOF >> $GITHUB_ENV

      - name: Get summary
        id: get-summary
        uses: actions/github-script@v7
        with:
          script: |
            const output = process.env.COVERAGE_OUTPUT;
            const summary = output.split('\n').find((line) => line.startsWith('All files'));
            const [file, stmtsPct, branchPct, funcsPct, linesPct] = summary
              .split(' | ')
              .map((cell) => cell.trim());
            return {
              stmtsPct,
              branchPct,
              funcsPct,
              linesPct,
            };

      - name: Generate badge
        uses: emibcn/badge-action@v2.0.3
        with:
          label: Coverage
          status: ${{ steps.get-summary.outputs.result }}%
          color: ${{
            steps.get-summary.outputs.result > 90 && 'green'              ||
            steps.get-summary.outputs.result > 80 && 'yellow,green'       ||
            steps.get-summary.outputs.result > 70 && 'yellow'             ||
            steps.get-summary.outputs.result > 60 && 'orange,yellow'      ||
            steps.get-summary.outputs.result > 50 && 'orange'             ||
            steps.get-summary.outputs.result > 40 && 'red,orange'         ||
            steps.get-summary.outputs.result > 30 && 'red,red,orange'     ||
            steps.get-summary.outputs.result > 20 && 'red,red,red,orange' ||
            'red' }}
          path: .github/badges/coverage.svg

      - name: Push badge
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -a -m "Update coverage badge"
          git push
