name: coverage

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run coverage
        run: |
          echo 'COVERAGE_OUTPUT<<EOF' >> $GITHUB_ENV
          pnpm run coverage >> $GITHUB_ENV
          echo EOF >> $GITHUB_ENV

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const output = process.env.COVERAGE_OUTPUT;
            const summary = output.split('\n').find(line => line.startsWith('All files'));
            const [file, stmts, branch, funcs, lines] = summary.split(' | ').map(cell => cell.trim());
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Coverage: ${lines}% Lines`
            });
