name: coverage

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Run coverage
        run: |
          echo 'COVERAGE<<EOF' >> $GITHUB_ENV
          pnpm run coverage >> $GITHUB_ENV
          echo EOF >> $GITHUB_ENV

      - name: Run script
        uses: actions/github-script@v7
        with:
          script: |
            const coverage = process.env.COVERAGE;
            const summary = coverage.split('\n').find(line => line.startsWith('All files'));
            const result = summary.split(' | ')[4].trim();
            console.log(result);
