name: labeler

on:
  pull_request:
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Label
        uses: actions/github-script@v7
        with:
          script: |
            const typeLabels = [
              'feat',
              'fix',
              'perf',
              'docs',
              'test',
              'refactor',
              'style',
              'build',
              'ci',
              'revert',
              'chore',
            ];
            const repoLabels = [...typeLabels, 'BREAKING CHANGE'];
            const prBody = context.payload.pull_request.body;
            const prLabels = (
              await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
              })
            ); // .map((label) => label.name);
            console.log(prLabels);
            const prTypeLabels = [];
            for (const label of repoLabels) {
              if (prBody.includes(`[x] ${label}: `)) {
                if (!prLabels.includes(label)) {
                  await github.rest.issues.addLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    name: label,
                  });
                }
                if (typeLabels.includes(label)) {
                  prTypeLabels.push(label);
                }
              } else if (prLabels.includes(label)) {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: label,
                });
              }
            }
            if (prTypeLabels.length !== 1) {
              core.setFailed(
                `One and only one type label must be set, tried [${prTypeLabels.join(', ')}]`,
              );
            }
